package Problems;

/**
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * 给定两个字符串 s 和 t，它们只包含小写字母。
 * 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。
 * 请找出在 t 中被添加的字母。
 *
 */

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] words = new int[26];
        for(char c : s.toCharArray()){
            words[c - 'a']++;
        }
        for(char c : t.toCharArray()){
            if(--words[c - 'a'] < 0){
                return c;
            }
        }
        return 'a';
    }
}
